version: '3'

services:
  app:
    build: .
    volumes:
      - .:/home/node/app
  db:
    image: bitnami/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nextauth
    ports:
      - "5432:5432"
    restart: always